Download rules and unarchive them
openclarity/yara-rule-server pull request #1
Opened 2023-08-23 08:03 UTC by pbalogh-sa

2023-09-08 14:06 UTC, Tehsmash requested changes

2023-09-08 14:06 UTC, Tehsmash commented on pkg/rules/rules.go
> +		if !prevStepFailed {
Not sure this is a sensible code structure, I suggest that we move this out into a separate function like:
```
// atomicDownloadAndReplace will download and unarchive the URL,
// only if those are successful will the data replace sourceDir
func atomicDownloadAndReplace(url, sourceDir) error {
   tmpdir, err := os.MkdirTemp(...)
   if err != nil {
       return fmt.Errorf(...., err)
   }

   err := downloadFile(...)
   if err != nil {
       return ...
   }
   
   err := unzip(...)
   if err != nil {
      return ...
   }
   
   err := os.RemoveAll(...)
   if err != nil {
      return ...
   }
   
   err := os.Rename(...)
   if err != nil {
      return ...
   }
}   
```

In this function it simple becomes:

```
		sourceDir := path.Join(config.CacheDir, "sources", source.Name)
		if err := os.MkdirAll(sourceDir, 0755); err != nil {
			logger.Errorf("failed to create directory for source %s: %v", sourceDir, err)
			continue
		}
		
		err := atomicDownloadAndReplace(url, sourceDir)
		if err != nil {
           logger.Errorf("unable to update source %s; using any existing data: %v", err)
		}
		
		yarFiles, err := createYarFileListToIndex(sourceDir, reg)
		if err != nil {
		   logger.Errorf(...)
		   continue
		}
```

2023-09-10 08:25 UTC, FrimIdan commented on pkg/rules/rules.go
> +		return fmt.Errorf("failed to create yara rule server temp directory. tempDir=%s error=%v", tempDir, err)
no need the `error=%v` we usually use only `:%w`, right?

2023-09-10 08:25 UTC, FrimIdan commented on pkg/rules/rules.go
> +			logger.Errorf("failed to create directory %s. Using the last successful download if available: error=%v", sourceDir, err)
no need the `error=%v` we usually use only `:%w`, right?

2023-09-10 08:27 UTC, FrimIdan commented on pkg/rules/rules.go
> +				logger.Errorf("failed to create temp directory for %s Using the last successful download if available: error=%v", source.Name, err)
please remove all the `error` from the error prints

2023-09-11 08:11 UTC, Tehsmash requested changes

2023-09-11 08:11 UTC, Tehsmash commented on pkg/rules/rules.go
> +			logger.Errorf("failed to create directory %s. Using the last successful download if available: %w", sourceDir, err)
As the linter said, %w is only for fmt.Errorf. When logging errors we should use:
```
logger.WithError(err).Errorf("words words words")
```

2023-09-11 08:14 UTC, Tehsmash requested changes

2023-09-11 08:14 UTC, Tehsmash commented on pkg/rules/rules.go
> +		return fmt.Errorf("failed to download rule source %s. Using the last successful download if available. URL=%s: %v", source.Name, source.URL, err)
should be %w for wrapping the error

2023-09-11 08:14 UTC, Tehsmash commented on pkg/rules/rules.go
> +		return fmt.Errorf("failed to unarchive source %s. Using last successful download if available. File=%s: %v", source.Name, fileName, err)
ditto

2023-09-11 08:14 UTC, Tehsmash commented on pkg/rules/rules.go
> +		return fmt.Errorf("failed to remove previous sources: %v", err)
ditto

2023-09-11 08:14 UTC, Tehsmash commented on pkg/rules/rules.go
> +		return fmt.Errorf("failed to move downloaded source: %v", err)
ditto

2023-09-12 07:48 UTC, pbalogh-sa commented on yara-rule-server-example
> +    exclude_regex: ".*index.*.yar|.*/utils/.*|.*/deprecated/.*|.*index_.*|.*MALW_AZORULT.yar"
I've opened an issue: https://github.com/openclarity/yara-rule-server/issues/6

2023-09-12 08:00 UTC, Tehsmash approved these changes
LGTM, there are a few more places which need the error wrapping fixed.

We can copy this https://github.com/openclarity/vmclarity/pull/668 and enable the linter to check this and fix it in a follow up.

2023-09-12 09:05 UTC, pbalogh-sa commented on pkg/rules/compile.go
> +		return fmt.Errorf("failed to run index_gen.sh: %v, %v", err, string(resultJsonB))
index_gen.sh is not used anymore

2023-09-12 09:05 UTC, pbalogh-sa commented on pkg/config/config.go
> +	IndexGenPath              string   `mapstructure:"index_gen_path"`
index_gen.sh is not used anymore

2023-09-12 10:57 UTC, akpsgit approved these changes

2023-09-12 11:01 UTC, merged